#pragma once

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <string>
#include <string_view>
#include <vector>

namespace rose::archives
{
    struct ZipArchiveEntry
    {
        std::string path;
        std::uint64_t uncompressedBytes{ 0 };
        std::uint64_t compressedBytes{ 0 };
        bool directory{ false };
        bool safeRelativePath{ true };
    };

    struct ZipArchiveListing
    {
        std::vector<ZipArchiveEntry> entries;
        std::size_t totalEntryCount{ 0 };
        std::uint64_t totalUncompressedBytes{ 0 };
        bool truncated{ false };
        bool containsUnsafePaths{ false };
    };

    struct ZipArchiveServiceConfig
    {
        // Listing is metadata-only, but still bounded so an intentionally huge ZIP
        // cannot flood Rose's context or temporary files.
        std::size_t maximumListedEntries{ 2000 };

        // Extraction/creation bounds are intentionally conservative for the first
        // archive-capability slice. They are configuration, not protocol constants.
        std::size_t maximumArchiveEntries{ 20000 };
        std::uint64_t maximumEntryBytes{ 512ull * 1024ull * 1024ull };
        std::uint64_t maximumTotalBytes{ 2ull * 1024ull * 1024ull * 1024ull };
    };

    // Abstract boundary so tools/tests do not depend directly on PowerShell or a
    // particular ZIP library. Future libarchive/miniz/plugin implementations can
    // replace the Windows backend without changing Agent/tool semantics.
    class IZipArchiveService
    {
    public:
        virtual ~IZipArchiveService() = default;

        [[nodiscard]]
        virtual ZipArchiveListing list(
            const std::filesystem::path& archivePath) const = 0;

        virtual void extract(
            const std::filesystem::path& archivePath,
            const std::filesystem::path& destinationDirectory) const = 0;

        virtual void create(
            const std::filesystem::path& sourcePath,
            const std::filesystem::path& destinationArchive) const = 0;
    };

    // Windows-local ZIP backend using System.IO.Compression through the installed
    // Windows PowerShell runtime. No network service, Office install, or cloud API
    // is required. Scripts are generated by Rose and receive paths only through
    // positional arguments; archive/source paths are never interpolated into code.
    class WindowsZipArchiveService final : public IZipArchiveService
    {
    public:
        explicit WindowsZipArchiveService(
            ZipArchiveServiceConfig config = {});

        [[nodiscard]]
        ZipArchiveListing list(
            const std::filesystem::path& archivePath) const override;

        void extract(
            const std::filesystem::path& archivePath,
            const std::filesystem::path& destinationDirectory) const override;

        void create(
            const std::filesystem::path& sourcePath,
            const std::filesystem::path& destinationArchive) const override;

        [[nodiscard]]
        const ZipArchiveServiceConfig& config() const noexcept;

    private:
        ZipArchiveServiceConfig config_;
    };

    // Platform-independent path predicate used by tests, manifest readers, and the
    // Windows extraction preflight. Backslashes and forward slashes are both
    // interpreted as archive separators. Absolute/drive-qualified/parent-traversal
    // entry names are rejected.
    [[nodiscard]]
    bool isSafeZipEntryPath(
        std::string_view entryPath) noexcept;
}
