#pragma once

#include "artifacts/Artifact.h"
#include "input/UserSubmission.h"
#include "workspace/WorkspaceTypes.h"

#include <condition_variable>
#include <cstdint>
#include <deque>
#include <mutex>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace rose::ui
{

    // Commands generated by Rose-owned desktop UI rather than typed chat text.
    // They share ChatBridge's existing wakeup/queue so the worker can remain
    // blocked without polling while still handling workspace actions promptly.
    enum class UiWorkerCommandType
    {
        CreateDiscussion,
        ActivateDiscussion,
        RemoveDiscussion,
        RestoreDiscussion,
        CreateProject,
        OpenProject,
        RemoveProject,
        RestoreProject
    };


    struct UiWorkerCommand
    {
        UiWorkerCommandType type{ UiWorkerCommandType::CreateDiscussion };
        std::string targetId;
    };


    using WorkerRequest =
        std::variant<
            input::UserSubmission,
            UiWorkerCommand>;


    struct ChatTranscriptTurn
    {
        std::string userText;
        std::string assistantText;
    };


    // Messages sent FROM Rose's worker TO the graphical frontend.
    enum class ChatEventType
    {
        AssistantStarted,
        AssistantText,
        AssistantFinished,
        ArtifactReady,
        ConversationCleared,
        ConversationReplaced,
        Notice,
        Notification,
        Error
    };


    struct ChatEvent
    {
        ChatEventType type{
            ChatEventType::AssistantText
        };

        std::string text;

        // Only populated for ArtifactReady. A value type is deliberate: the worker
        // transfers a durable path/metadata description, never an SDL resource.
        std::optional<artifacts::Artifact> artifact;

        // Only populated for ConversationReplaced. This is presentation data, not
        // a second persistence model: the worker copies the selected discussion's
        // canonical stored turns so the UI can reconstruct its visible transcript.
        std::vector<ChatTranscriptTurn> transcriptTurns;
    };


    struct WorkspaceSnapshotUpdate
    {
        std::uint64_t version{ 0 };
        workspace::WorkspaceSnapshot snapshot;
    };


    // -----------------------------------------------------------------------------
    // ChatBridge
    // -----------------------------------------------------------------------------
    //
    // Thread boundary between the SDL/UI thread and Rose's worker.
    //
    // UI -> worker carries either one UserSubmission or a small Rose-owned UI
    // command. Worker -> UI carries chat events plus a versioned lightweight
    // workspace snapshot. Model/provider objects and SDL resources never cross.
    class ChatBridge final
    {
    public:
        void submitUserSubmission(
            input::UserSubmission submission);

        // Convenience path retained for simple text-only callers/tests.
        void submitUserMessage(
            std::string message);

        void submitUiCommand(
            UiWorkerCommand command);

        [[nodiscard]]
        std::optional<WorkerRequest>
            waitForWorkerRequest();


        void postEvent(
            ChatEvent event);

        [[nodiscard]]
        std::optional<ChatEvent> tryPopEvent();


        void publishWorkspaceSnapshot(
            workspace::WorkspaceSnapshot snapshot);

        [[nodiscard]]
        std::optional<WorkspaceSnapshotUpdate>
            workspaceSnapshotSince(
                std::uint64_t knownVersion) const;


        void requestShutdown();

        [[nodiscard]]
        bool shutdownRequested() const;

    private:
        mutable std::mutex mutex_;

        std::condition_variable requestAvailable_;

        std::deque<WorkerRequest> workerRequests_;

        std::deque<ChatEvent> events_;

        workspace::WorkspaceSnapshot workspaceSnapshot_;
        std::uint64_t workspaceSnapshotVersion_{ 0 };

        bool shutdownRequested_{ false };
    };

} // namespace rose::ui
