#pragma once

#include "tools/ITool.h"

#include <cstddef>
#include <filesystem>

namespace rose::tools
{

    struct ApplyRenamePlanToolConfig
    {
        std::size_t maximumOperations{ 2048 };
    };


    // Applies one Rose-owned rename plan after explicit confirmation.
    // The plan itself is generated by PlanDirectoryDocumentRenamesTool and is
    // revalidated before any filesystem mutation occurs.
    class ApplyRenamePlanTool final : public ITool
    {
    public:
        explicit ApplyRenamePlanTool(
            std::filesystem::path planDirectory,
            ApplyRenamePlanToolConfig config = {});

        [[nodiscard]]
        const ToolDescriptor& descriptor() const noexcept override;

        [[nodiscard]]
        ToolResult execute(
            const ToolRequest& request) override;

    private:
        std::filesystem::path planDirectory_;
        ApplyRenamePlanToolConfig config_;
        ToolDescriptor descriptor_;
    };

} // namespace rose::tools
